In [1]:
import pandas as pd

In [16]:
dataset = pd.read_csv('resume_dataset.csv',)

In [17]:
dataset.shape

(1219, 3)

In [18]:
dataset.head()

   ID Category                                             Resume
0   1       HR  b'John H. Smith, P.H.R.\n800-991-5187 | PO Box...
1   2       HR  b'Name Surname\nAddress\nMobile No/Email\nPERS...
2   3       HR  b'Anthony Brown\nHR Assistant\nAREAS OF EXPERT...
3   4       HR  b'www.downloadmela.com\nSatheesh\nEMAIL ID:\nC...
4   5       HR  b"HUMAN RESOURCES DIRECTOR\n\xef\x82\xb7Expert...

In [19]:
print(dataset.loc[0]['Resume'].decode("utf-8"))

AttributeError: 'str' object has no attribute 'decode'

In [26]:
dataset['Category'].unique()

array(['HR', 'Designing', 'Managment', 'Information Technology',
       'Education', 'Advocate', 'Business Development',
       'Health & Fitness', 'Agricultural', 'BPO', 'Sales', 'Consultant',
       'Digital Media', 'Automobile', 'Food & Beverages', 'Finance',
       'Apparel', 'Engineering', 'Accountant', 'Building & Construction',
       'Architects', 'Public Relations', 'Banking', 'Arts', 'Aviation'],
      dtype=object)

In [20]:
dataset.loc[0]['Resume']

"b'John H. Smith, P.H.R.\\n800-991-5187 | PO Box 1673 | Callahan, FL 32011 | info@greatresumesfast.com\\n\\nApproachable innovator with a passion for Human Resources.\\n\\nSENIOR HUMAN RESOURCES PROFESSIONAL\\nPersonable, analytical, flexible Senior HR Professional with multifaceted expertise. Seasoned Benefits Administrator with\\nextensive experience working with highly paid professionals in client-relationship-based settings. Dynamic team leader\\ncapable of analyzing alternatives and identifying tough choices while communicating the total value of benefit and\\ncompensation packages to senior level executives and employees.\\n\\nCORE COMPETENCIES\\nBenefits Administration \\xe2\\x80\\x93 Customer Service \\xe2\\x80\\x93 Cost Control \\xe2\\x80\\x93 Recruiting \\xe2\\x80\\x93 Acquisition Management \\xe2\\x80\\x93 Compliance Reporting\\nRetention \\xe2\\x80\\x93 Professional Services \\xe2\\x80\\x93 Domestic & International Benefits \\xe2\\x80\\x93 Collaboration \\xe2\\x80\\x93 Adaptability \\xe2\\x80\\x93 Change Management\\nDefined Contribution Plans \\xe2\\x80\\x93 Auditing \\xe2\\x80\\x93 Negotiation \\xe2\\x80\\x93 Corporate HR Policies \\xe2\\x80\\x93 Full Lifecycle Training \\xe2\\x80\\x93 401(k) \\xe2\\x80\\x93 Form 5500\\nConfidential Files \\xe2\\x80\\x93 EEO-1 \\xe2\\x80\\x93 AAP \\xe2\\x80\\x93 FMLA \\xe2\\x80\\x93 STD \\xe2\\x80\\x93 LTD \\xe2\\x80\\x93 H1-B Visa \\xe2\\x80\\x93 Vets 100 \\xe2\\x80\\x93 EAP \\xe2\\x80\\x93 Processing Payroll\\n\\nHR TECHNOLOGY\\n\\nHRIS Data Management & Auditing \\xe2\\x80\\x93 Ultipro Back Office \\xe2\\x80\\x93 Ultipro Web Connect\\nDeltek Costpoint \\xe2\\x80\\x93 Deltek GCS Premiere \\xe2\\x80\\x93 Cognos \\xe2\\x80\\x93 ADP\\n\\nProfessional Experience\\nHUMAN SERVICES, INC. \\xe2\\x80\\x93 Tampa, FL\\n\\n2010\\xe2\\x80\\x93Present\\n\\nProviding institutional behavioral health and medical management contracting services | 2,500 employees\\n\\nBenefits Manager\\nManage and administer a robust $13M health and welfare program; administer benefits programs for two smaller\\nminority business enterprise clients. Deliver excellence in client services, leveraging interpersonal skills to establish\\nrapport with team members. Perform cost analysis, gather claims data, coordinate enrollment and more for a large selffunded medical plan plus two smaller fully-insured plans. Analyze data and projections to create forecasts in narrative\\nand graph format; clearly and succinctly communicate trends to senior management in meetings. Directly supervise\\nstaff of 3: HR Admin, plus two Human Resource specialists.\\n\\xef\\x81\\xb3 Lead Healthcare Reform change management process, analyzing changes, developing strategic plans, and\\n\\ntimeline for crucial decisions ahead of 2014 deadlines. Communicate early changes in dependent coverage,\\npreventive care, and lifetime maximum benefits to employees.\\n\\n\\xef\\x81\\xb3 Identified, researched, and implemented HSA (Healthcare Savings Account) health insurance option for high-\\n\\ndeductible health insurance plan to provide tax-sheltered benefits for physicians and other high-income, highprofile professionals.\\n\\n\\xef\\x81\\xb3 Saved $30K annually by restructuring the open enrollment strategy, leveraging existing human capital and HR\\n\\nbusiness partners to achieve better communication at lower cost.\\n\\n\\xef\\x81\\xb3 Quickly establish rapport with employees; balance client-relationship needs with organizational goals, cost\\n\\ncontrols, and compliance requirements to create a positive work environment.\\n\\n\\xef\\x81\\xb3 Maximize employee recruiting and retention by implementing competitive benefits packages and clearly\\n\\ncommunicating their value to team members.\\n\\n\\xef\\x81\\xb3 Reduced costs $20K per year by collaborating closely with legal department to create an in-house total comp\\n\\nstatement including implications for taxes and social security; produced a better-quality analysis at lower costs.\\n\\n\\x0cJohn H. Smith, P.H.R. \\xe2\\x80\\x93 PAGE 2\\n\\n800-991-5187|info@greatresumesfast.com\\n\\nApproachable innovator with a passion for Human Resources.\\nHUMAN MANAGEMENT INC. \\xe2\\x80\\x93 Atlanta, GA\\n\\n2008\\xe2\\x80\\x932010\\n\\nNonprofit government consulting firm | 1,200 domestic and international employees\\n\\nSenior Human Resources Generalist\\nPerformed diverse Human Resources functions: administered benefits, led special projects, updated policies,\\ncollaborated on EEO-1, Vets 100, and Affirmative Action Plan (AAP) reporting. Revamped orientation and training\\nprograms for newly hired employees to include comprehensive information delivered in more-personal formats:\\nteleconferences, small group meetings, tours, and one-on-one conversations, with follow-up phone calls. Supervised HR\\nAssistant and up to 3 temporary Human Resource specialists handling high volume of work during peak periods such as\\nopen enrollment and company merger.\\n\\xef\\x81\\xb3 Led change management process that seamlessly integrated benefits, compensation, retirement plans, and\\n\\nlogistics for newly acquired company with 60+ employees; prepared all-encompassing reports on total\\ncompensation plans.\\n\\n\\xef\\x81\\xb3 Developed webinars and personal meetings to communicate value of benefits to employees despite reductions\\n\\nduring an economic recession; maintained employee retention and job satisfaction rankings despite cutbacks.\\n\\n\\xef\\x81\\xb3 Reduced overall benefit costs 10% including a decrease in STD benefits from 100% to 75% of base\\n\\ncompensation without significant increase in employee turnover.\\n\\n\\xef\\x81\\xb3 Researched and procured benefits for government contractors traveling to hazardous areas including Kidnap &\\n\\nRansom (K&R), increased life insurance, and travel insurance.\\n\\n\\xef\\x81\\xb3 Identified and implemented medical and dental benefit plans to ensure comparable compensation for\\n\\ninternational employees worldwide.\\n\\n\\xef\\x81\\xb3 Managed diverse retirement plans including defined contribution 403(b), 401(a), and executive 457(b) plans.\\n\\nABC CORPORATION \\xe2\\x80\\x93 New York, NY\\n\\n2007\\xe2\\x80\\x932008\\n\\nEngineering and Construction consulting | 500 international and domestic employees\\nSenior Human Resources Generalist\\nACME, INC. \\xe2\\x80\\x93 Washington, D.C.\\n\\n2004\\xe2\\x80\\x932006\\n\\nProfessional services consulting firm | 300 employees\\nHR Generalist / Benefits Specialist\\n\\nHUMAN RESOURCE CORPORATION \\xe2\\x80\\x93 Tampa, FL\\nIT & environmental management consulting firm | 300 employees\\nHuman Resources Assistant\\n\\nEducation, Certification, & Affiliation\\nBachelor of Science in Psychology, 2002\\nCOMMUNITY COLLEGE\\nProfessional in Human Resources (PHR) Certificate, 2010\\nEmployee Benefit Specialist (CEBS), Certification Pending\\nMember SHRM \\xe2\\x80\\x93 Society for Human Resource Management\\n\\n2002\\xe2\\x80\\x932004'"

In [21]:
dataset2 = pd.read_csv('resumes.csv')

In [22]:
dataset2.shape

(4870, 30)

In [23]:
dataset2.head()

,job_ad_id,job_city,job_industry,job_type,job_fed_contractor,job_equal_opp_employer,job_ownership,job_req_any,job_req_communication,job_req_education,...,honors,worked_during_school,years_experience,computer_skills,special_skills,volunteer,military,employment_holes,has_email_address,resume_quality
0,384,Chicago,manufacturing,supervisor,NaN,1,unknown,1,0,0,...,0,0,6,1,0,0,0,1,0,low
1,384,Chicago,manufacturing,supervisor,NaN,1,unknown,1,0,0,...,0,1,6,1,0,1,1,0,1,high
2,384,Chicago,manufacturing,supervisor,NaN,1,unknown,1,0,0,...,0,1,6,1,0,0,0,0,0,low
3,384,Chicago,manufacturing,supervisor,NaN,1,unknown,1,0,0,...,0,0,6,1,1,1,0,1,1,high
4,385,Chicago,other_service,secretary,0.0,1,nonprofit,1,0,0,...,0,1,22,1,0,0,0,0,1,high

In [24]:
dataset2.columns

Index(['job_ad_id', 'job_city', 'job_industry', 'job_type',
       'job_fed_contractor', 'job_equal_opp_employer', 'job_ownership',
       'job_req_any', 'job_req_communication', 'job_req_education',
       'job_req_min_experience', 'job_req_computer', 'job_req_organization',
       'job_req_school', 'received_callback', 'firstname', 'race', 'gender',
       'years_college', 'college_degree', 'honors', 'worked_during_school',
       'years_experience', 'computer_skills', 'special_skills', 'volunteer',
       'military', 'employment_holes', 'has_email_address', 'resume_quality'],
      dtype='object')

In [28]:
import os
os.listdir('./Resumes')

['Venkat_BA.docx',
 'Shashank.docx',
 'Anudeep N_Sr Java Developer.docx',
 'ram nandyala.docx',
 'Neha Mugghala.docx',
 'chenna kesava.docx',
 'Utthan Silawal12.docx',
 'Yohan BSA.docx',
 'Madhu_BA_AW.DOCX',
 'KIRAN KUMAR.docx',
 'avinash G.docx',
 'Harika_java.docx',
 'Mounika_P.docx',
 'HARI_Sr.Java Developer.docx',
 'RaviRaju_Resume.docx',
 'B Shaker-Sr BSA-Scrum Master .docx',
 'Vamshi Teja_Business Analyst.docx',
 'VIJETHA G.docx',
 'SaravanaKumar.docx',
 'Abiral_Pandey_Fullstack_Java.docx',
 'Manohar Reddy.docx',
 'Syed_Zia_Ashraf.docx',
 'srinivas b.docx',
 'Gururaja Murthy PMCPCSM.docx',
 'Madhuri Pawar.docx',
 'Sr. Business Analyst.docx',
 'Naveen Kumar Bandela.docx',
 'mohid_rj.docx',
 'Nikki_Nimmagadd.docx',
 'Chandler_BA.docx',
 'Ramteja Motupalli.docx',
 'Sri Gati.docx',
 'Rajesh_k.docx',
 'Ashok Jayakumar - PM.docx',
 'Sahithi K.docx',
 'Deepika Chintalapati.docx',
 'RaviBurra_Certified PM_DevOps.docx',
 'Business Analyst_GHyma.docx',
 'Vivek.BSA.docx',
 'Gokul Selvam S PM.docx',
 'Naveen Arora.docx',
 'jagadeesh k.docx',
 'BA Kiran.docx',
 'Gopi.docx',
 'Raja Santhosam_PM Scrum Master.DOCX',
 'Resume - PM Agile-Scrum.docx',
 'Satish Uduta.docx',
 'Othman - Project Manager.docx',
 'Satish Reddy.docx',
 'Priya_Sharma.docx',
 'Sai Krishna BA.docx',
 'Nandini_Resume.docx',
 'Vivek Joshi_CV.docx',
 'indrakaran soma.docx',
 'Priyanka Sr BSA Resume.docx',
 'Shaker Resume.docx',
 'Tarun Resume.docx',
 'Rajendra-PMP-CSM.docx',
 'Akhil.profile.docx',
 'Mohamad Jamil.docx',
 'Pierre John.docx',
 'Derik.docx',
 'Dantu Padmasri - Project Manager.docx',
 'Vamshi L.docx',
 'Resume Vishal PM - MSIS, PMP-PMI.docx',
 'Deepika DC.docx',
 'MounikaReddy.docx',
 'manish_singh_resume.docx',
 'Smita Kamble_Resume.docx',
 'nithin katapally.docx',
 'harish S.docx',
 'ravikiran JALASUTRAPU.docx',
 'Nilesh-resume_1_phplead.docx',
 'AnilAgarwal.docx',
 'Francis Gomes Resume.docx',
 'Avathika BA-Healthcare_.docx',
 'Shiva G-Java Resume.docx',
 'madhuri R.docx',
 'Komala BSA Resume.docx',
 'Tanmay_Dam_Resume_BA.docx',
 'Randy Adams.docx',
 'Balakrishna Sudabathula.docx',
 'Amulya Komatineni.docx',
 'Krishnapriya_BA.docx',
 'Ravi Pattar- Sr. Agile Program manager.docx',
 'Pavan Kumar Full Stack Java Developer.docx',
 'Krishna_BSA.docx',
 'Sai Srinivas_Sr_Java_Developer.docx',
 'employer_mounika details.docx',
 'Samir Naik-NJ - Mar 2018-V3.0.docx',
 'Vishnu J.docx',
 'Bharatha BA Resume.docx',
 'Vijay Bhargav.docx',
 'Praveen B.docx',
 'Vikash_BA_Ab.docx',
 'Manohar B.docx',
 'sai k.docx',
 'TeresaNeetipudi IT BA.DOCX',
 'Varun.docx',
 'Priya B.docx',
 'PM RESUME.docx',
 'Harish K.docx',
 'madhuri_java.docx',
 'Kuppurajbabu_BA.docx',
 'Kumar Raj.docx',
 'Kashyap K. Vora resume.docx',
 'Mahesh_Kamath_PM (1).docx',
 'Naren Sr.BA.docx',
 'Mitali Barman_Resume.docx',
 'Manikanta P.docx',
 'Adelina_Erimia_PMP1.docx',
 'Jennifer  M. Conte.docx',
 'Tarun_Developer.docx',
 'Sougandh_Java Fullstack Developer.docx',
 'Mani_Hadoop.docx',
 'Balaji Gopalakrishnan Project Manager.docx',
 'Jagan S Iyer PM.docx',
 'Dave.docx',
 'Mounika health care resume.docx',
 'Prashant Chawda_resume.docx',
 'Pranay P.docx',
 'Vinay.D_Resume.docx',
 'Yugesh_Resume.docx',
 'komal patel.docx',
 'Sarath M.docx',
 'manohar.B.docx',
 'kalyan das.docx',
 'Sai kumar.docx',
 'SAURABH_PM.docx',
 'ParthMPatel_BA.docx',
 'Samir Naik-NJ - Feb 2018-V6.0.docx',
 'Naren Sr.BA .docx',
 'Krishna Sr. BSA Resume.docx',
 'Ramachandra EDA.docx',
 'Tarun RESUME-BSAT.docx',
 'Sudhakar Reddy.docx',
 'ram krishna.docx',
 'BA - Navneet.docx',
 'Pavan Sr Business Analyst resume.docx',
 'Tejaswi-resume.docx',
 'Srivatsan_Project_Manager.docx',
 'Ashwini J2EE Developer.docx',
 'Rashmitha R.docx',
 'Shail_Tank-Business Analyst .docx',
 'Atul_Mathur_Resume.docx',
 'Drakshajavauidev.docx',
 'Nikith Reddy.docx',
 'Praveen T.docx',
 'Naveen.S_Resume.docx',
 'BA with INV.docx',
 'Resume_Spoorti Pandit_BSA.docx',
 'Saiteja G.docx',
 'Alekhya Resume.docx',
 'Shelly Woods.docx',
 'Resume - Sr PM.docx',
 'Krishna Kuruvella.docx',
 'Ravi Reddy.docx',
 'Vishnu BA Resume.docx',
 'ronith s.docx',
 'Rohanu Resume.docx',
 'Sravani Battu.docx',
 'Sumanth Manne Java Developer.docx',
 'Ujvala BA Feb 20.docx',
 'Uday_Maripelly.docx',
 'Krishna_SrJava.docx',
 'Achyuth Resume_8.docx',
 'Sahas BA Resume.docx',
 'Dhanalaxmi -BA.docx',
 'Bharat Arora_CV_PMP _ ERP1.docx',
 'Rao_Java.docx',
 'Bapuji Hadoop developer.docx',
 'Jayadattaperi N.docx',
 'Varun Kumar.docx',
 'jeck P.docx',
 'Jimi_Desai_PM.docx',
 'Mehul.docx',
 'Sravani Singirikonda.docx',
 'Tushar Patel.docx',
 'Amar Sr BSA.docx',
 'Gautami Bulusu Mobile Testing 3.docx',
 'Niteesh Java Developer.docx',
 'Vishal S..docx',
 'Mohammad Resume.docx',
 'vema reddy.docx',
 'nithin Reddy.docx',
 'Jaya prakash.docx',
 'Amrinder Business Analyst.docx',
 'Resume2018March.docx',
 'Resume - Kishore Kotapati - 218E - BA.docx',
 'Raju Goduguchinta_Technical Program Manager.docx',
 'Spoorthi Finance BSA Resume.docx',
 'Shiuli Mahmud.docx',
 'Naresh V.docx',
 'Tarun.docx',
 'RAMYA BUSINESS ANALYST RESUME.docx',
 'vikas java.docx',
 'BA - Abhishek.docx',
 'Sharath Java.docx',
 'mahesh_Java.docx',
 'Reddemma_Lankipalle.docx',
 'mounika BA resume 7.docx',
 'Anil Krishna Mogalaturthi.docx',
 'Murali_Project Manager QA.DOCX',
 'sanjay kumar.docx',
 'KY BA PM UPDATED RESUME .docx',
 'Brahma-Resume (BA).docx',
 'Robinson.docx',
 'venu b.docx',
 'Ami Jape.docx',
 'Siddhartha Gandroju.docx',
 'Adhi Gopalam - SM.docx',
 'Pankaj BSA.docx',
 'Ranjan_Project Manager-Scrum Master.docx',
 'CHETAN_Sr Java Developer.docx',
 'Santosh Arugula BA.docx',
 'Akhil_Sr BSA.docx',
 'Sundar_Java_8+ Years..docx',
 'SUNITHA Project Manager (1).docx',
 'sairithvik alla.docx',
 'Haarika_BA.docx',
 'AjayKumar.docx',
 'Nikhil.docx',
 'B Suresh Kumar_Project Manager_1.docx',
 'Harshitha Challa.docx',
 'Venkata_Sr.PHP_Developer.docx',
 'V Ashok A.docx',
 'Navneeth Resume.docx',
 'Vishnu Java dev.docx']

In [33]:
with open('./Resumes/Venkat_BA.docx','rb') as fp:
    print(fp.readlines()[0].decode('utf-8'))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 22: invalid start byte